name: spotify
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/vectors/
    - assets/images/

  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Regular.ttf
          weight: 400 # Regular
        - asset: fonts/Satoshi-Light.ttf
          weight: 300 # Light
        - asset: fonts/Satoshi-Medium.ttf
          weight: 500 # Medium
        - asset: fonts/Satoshi-Bold.ttf
          weight: 700 # Bold
        - asset: fonts/Satoshi-Black.ttf
          weight: 900 # Black
        - asset: fonts/Satoshi-Italic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
