// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBetfE48ZdBIiYGLpb3jdzHefpaDJCCE-M',
    appId: '1:89812360018:web:14bde3b34f02dadc7df88b',
    messagingSenderId: '89812360018',
    projectId: 'spotify0x',
    authDomain: 'spotify0x.firebaseapp.com',
    storageBucket: 'spotify0x.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg_md48lrfDpdolSac6JOZg7yj7mNn5Ac',
    appId: '1:89812360018:android:bf84f60d294fa6d97df88b',
    messagingSenderId: '89812360018',
    projectId: 'spotify0x',
    storageBucket: 'spotify0x.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIICHKV-ndBsOlD4MI7aoufdHq0s0EUy8',
    appId: '1:89812360018:ios:6604645bc972264f7df88b',
    messagingSenderId: '89812360018',
    projectId: 'spotify0x',
    storageBucket: 'spotify0x.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );
}
